### ISSUE TITLE
document_intelligence is not working

### ISSUE THREAD

**Issue by huaxing-233** [microsoft/markitdown#1168]
```python
from markitdown import MarkItDown

md = MarkItDown(docintel_endpoint="<document_intelligence_endpoint>")
result = md.convert("test.pdf")
print(result.text_content)
```

code is throwing this error 

```bash
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        AzureCliCredential: Azure CLI not found on path
        AzurePowerShellCredential: PowerShell is not installed
        AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
CropBox missing from /Page, defaulting to MediaBox

```

same set up with document_intelligence sdk is working, any idea why?

I am pretty I have the endpoint url and api key set up properly

**Comment by afourney** [comment]
Ahh yes, it's because the default uses managed identity.  This PR should solve the problem I think: https://github.com/microsoft/markitdown/pull/1151

Try setting the "AZURE_API_KEY" environment variable.

Otherwise, 

You can do:

```
md = MarkItDown(docintel_endpoint="<document_intelligence_endpoint>", docintel_credential=AzureKeyCredential("<your_key>"))
```

**Comment by huaxing-233** [comment]
> Ahh yes, it's because the default uses managed identity. This PR should solve the problem I think: [#1151](https://github.com/microsoft/markitdown/pull/1151)
> 
> Try setting the "AZURE_API_KEY" environment variable.
> 
> Otherwise,
> 
> You can do:
> 
> ```
> md = MarkItDown(docintel_endpoint="<document_intelligence_endpoint>", docintel_credential=AzureKeyCredential("<your_key>"))
> ```

thanks for the reply, I think I am using the latest code with your fix and I tried with your suggestion, but still get the same error 
it is kind of strange, because they way you use 
```python
document_intelligence_client = DocumentIntelligenceClient(
        endpoint=endpoint, credential=AzureKeyCredential(key)
    )
```
seems pretty solid to me, I will try to attach a debugger and see why

**Comment by afourney** [comment]
Thanks! The option is pretty new, so any help on this front is appreciated. It’s meant to work, and we'll shake out the bugs I'm sure.

**Comment by basshbj** [comment]
Hi,
I am having the same issue. Cannot make it work, although for me is not giving any error, it just extracts plain text from the pdf. Not sure why this happens, still debugging.

But I notice that that PR is not included in the last release (v0.1.1), so that may be the reason why is not working.
In the below code the `docintel_credential` is missing
[v0.1.1 - packages/markitdown/src/markitdown/_markitdown.py](https://github.com/microsoft/markitdown/blob/v0.1.1/packages/markitdown/src/markitdown/_markitdown.py#L198)

**Comment by Isydmr** [comment]
@afourney A release would be great—`docintel_credential` isn’t working for me either.

**Comment by saibhaskerraju** [comment]
@afourney 
although this PR is merged, I guess its not published. we are not seeing these changes in latest version. please check

**Comment by saibhaskerraju** [comment]
@afourney 

please publish this commit. we want to use this ASAP
https://github.com/microsoft/markitdown/commit/9e067c42b647eaf14e842e70e47540b36c0c4a08

**Comment by afourney** [comment]
@saibhaskerraju there have been other large changes (formula extraction for word documents) that I want a little more feedback on before I publish a new release (e.g., to PyPi).  That said, I'll see if I can publish a pre-release today to make it available for easier distribution.

**Comment by kuroponzu** [comment]
FYI
It worked when I changed it to v0.1.2 and did the following

```
from markitdown import MarkItDown
from azure.core.credentials import AzureKeyCredential
ALLOWED_EXTENSIONS = ['pdf']

md = MarkItDown(docintel_endpoint = "<document_intelligence_endpoint>", docintel_file_types = ALLOWED_EXTENSIONS, docintel_credential = AzureKeyCredential("<azure_api_key>"))

result = md.convert('test.pdf')

print(result.text_content)
```

**Comment by bhavyajoshi-mahindra** [comment]
I have tired the document intelligent but there is no image description added in the final markdown file. 


```
import os
from markitdown import MarkItDown
from dotenv import load_dotenv
load_dotenv()
from azure.core.credentials import AzureKeyCredential

AZURE_DOC_INT_ENDPOINT = os.getenv("AZURE_FORM_RECOGNIZER_ENDPOINT")
AZURE_DOC_INT_KEY = os.getenv("AZURE_FORM_RECOGNIZER_KEY")
os.environ["AZURE_API_KEY"] = AZURE_DOC_INT_KEY

def save_to_markdown(output_dir: str, filename: str, text: str):
    os.makedirs(output_dir, exist_ok=True)
    markdown_path = os.path.join(output_dir, filename)
    with open(markdown_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Saved: {markdown_path}")

# Input/output folders
input_folder = "sop"
output_folder = "markdowns2"

# Initialize MarkItDown
md = MarkItDown(docintel_endpoint = AZURE_DOC_INT_ENDPOINT, 
                docintel_file_types = ['pdf'],
                docintel_credential = AzureKeyCredential(AZURE_DOC_INT_KEY))

# Loop through all PDF files
for file in os.listdir(input_folder):
    if file.lower().endswith(".pdf"):
        pdf_path = os.path.join(input_folder, file)
        print(f"🔄 Converting: {pdf_path}")
        result = md.convert(pdf_path)
        markdown_filename = os.path.splitext(file)[0] + ".md"
        save_to_markdown(output_folder, markdown_filename, result.markdown)
```
