### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 1195: illegal multibyte sequence

### ISSUE THREAD

**Issue by ArchieZhao** [microsoft/markitdown#198]
Traceback (most recent call last):
  File "D:\Program\AnacondaEnv\markitdown_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program\AnacondaEnv\markitdown_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program\AnacondaEnv\markitdown_env\Scripts\markitdown.exe\__main__.py", line 7, in <module>
  File "D:\Program\AnacondaEnv\markitdown_env\lib\site-packages\markitdown\__main__.py", line 43, in main
    print(result.text_content)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 1195: illegal multibyte sequence

**Comment by hanchan78** [comment]
Similar issues with me:
UnicodeEncodeError: 'charmap' codec can't encode character '\u2003' in position 3849: character maps to <undefined>

On another document:
UnicodeEncodeError: 'charmap' codec can't encode character '\uf416' in position 6988: character maps to <undefined>

**Comment by fishfen** [comment]
I encountered the same problem too.
UnicodeEncodeError: 'gbk' codec can't encode character '\u2217' in position 37: illegal multibyte sequence

**Comment by fishfen** [comment]
find solution here [https://github.com/microsoft/markitdown/issues/138#issuecomment-2553156636](url)

**Comment by tonygeneral** [comment]
I encounter the same problem too [meidi2023.pdf](https://github.com/user-attachments/files/18239638/meidi2023.pdf)

**Comment by l-lumin** [comment]
I think it was fixed in PR #116

**Comment by skybambler** [comment]
still not working..same issue.

UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 921: illegal multibyte sequence

**Comment by afourney** [comment]
The reported stdout encoding crash is addressed on main. For saved Markdown, please use markitdown input.pdf -o output.md (with your actual input filename). The -o option introduced in #116 writes UTF-8 directly and preserves characters that the terminal cannot represent; terminal output may replace unsupported characters.

Closing this encoding report as resolved. Please ask to reopen if the crash persists with the updated code, including your version and complete traceback.
